name: Java CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run grade install
      run: gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Compile with javac
      run: |
        find src -name "*.java" > sources.txt
        javac -d . -cp .:$(echo src/**/*.java | tr ' ' ':') @sources.txt
    - name: Run Application
      run: java -cp .:src Application
